openshift-labs/learn-katacoda

introduction/port-forwarding/env-init.sh
introduction/service-binding/env-init.sh
introduction/training-workshop/env-init.sh
introduction/transferring-files/env-init.sh

This is principally to avoid problems with templates not being loaded due to openshift project being slow to be created. The launch.sh and env-init.sh files actually run in parallel and openshift project is created from launch.sh but want to load templates into it from env-init.sh.

Fix up ordering in env-init.sh and add checks for openshift project.

---

introduction/port-forwarding/env-init.sh
playgrounds/openshift36/env-init.sh
playgrounds/openshift37/env-init.sh

The env-init.sh runs in parallel to user doing stuff. If user logs in quickly it can prevent commands running as no longer admin. This PR addresses that for port forwarding example by using impersonation to run things as admin. Will need to do similar for all other scenarios.

Address ordering issues with env-init.sh.

---

serverless/1-simple-nodejs-greeting/assets/setup-environment.sh
serverless/3-web-accessible-actions/assets/setup-environment.sh
serverless/4-chained-actions/assets/setup-environment.sh
serverless/5-rules-triggers/assets/setup-environment.sh

It appears that sometimes the oc patch route that is part of the env is not getting executed.  Add a second call to make sure it happens.  It is idempotent.

Add oc patch route

---

middleware/amq-getting-started-broker/02-create-broker-instance.md

Correct the katacoda docs in the console for amq-getting-started-broker example when template has been updated to openshift/amq-broker-71-basic from -63.

Update AMQ docs output from template amq-63 to amq-71

---

servicemesh/1-introduction/finish.md
servicemesh/1-introduction/index.json
servicemesh/1-introduction/run-init.sh
servicemesh/2-deploy-microservices/finish.md
servicemesh/2-deploy-microservices/index.json
servicemesh/2-deploy-microservices/run-init.sh
servicemesh/3-monitoring-tracing/finish.md
servicemesh/3-monitoring-tracing/index.json
servicemesh/3-monitoring-tracing/run-init.sh
servicemesh/4-simple-routerules/finish.md
servicemesh/4-simple-routerules/index.json
servicemesh/4-simple-routerules/run-init.sh
servicemesh/5-advanced-routerules/5rate-limit.md
servicemesh/5-advanced-routerules/finish.md
servicemesh/5-advanced-routerules/index.json
servicemesh/5-advanced-routerules/run-init.sh
servicemesh/6-fault-injection/finish.md
servicemesh/6-fault-injection/index.json
servicemesh/6-fault-injection/run-init.sh
servicemesh/7-circuit-breaker/finish.md
servicemesh/7-circuit-breaker/index.json
servicemesh/7-circuit-breaker/run-init.sh
servicemesh/8-egress/finish.md
servicemesh/8-egress/index.json
servicemesh/8-egress/run-init.sh

This PR contains the following improvements/fixes
- At the end of every scenarios, there is a link to https://developers.redhat.com/books/introducing-istio-service-mesh-microservices/
- Replace "Sleep 20" to wait OpenShift to be started in order to install the microservices and Istio
- The code is pulled from https://github.com/redhat-developer-demos/istio-tutorial/ using the *katacoda* branch.
- Removed /root/projects/incubator-openwhisk-devtools as it is not related to this scenario
- Rate Limiting is now working.

Several improvements for Servicemesh scenarios

---

middleware/fuse-hello-world/01-creating-an-initial-project.md
middleware/fuse-hello-world/02-deploying-first-fuse-application-on-openshift.md

- Markdown of a caption
- Rename 'JBoss Developer Studio' to the current name of the product 'Red Hat Developer Studio'
Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>

Fix 'middleware/fuse-hello-world' scenario

---

environments/openshift-3-10/scripts/middleware-pull.sh

Some scenarios like JWT and RBAC requires keycloak

Include Keycloak image for new Istio scenarios

---

environments/openshift-3-10/scripts/op-sdk-setup.sh

This script contains the necessary additional steps to install the operator-sdk tooling, as well as some env updates required for the training modules.  This script has been tested with the existing 3-10 environment.  We would like to get this built into a custom-env vs user having to run as first step in training.

Operator SDK installation script for new custom Openshift 3-10 environment

---

ansibleop/ansible-operator-overview/assets/op-sdk-setup.sh
environments/openshift-3-11/scripts/10_op-sdk-setup.sh

@BenHall @mhausenblas  - We need to update the script for operator-sdk in 3.11 env and rebuild image.  This will provide stability, as we are tagging us to a known release and newer version of golang.

Updating operator-sdk scripts to v0.2.0 release and 1.10 golang.

---

environments/openshift-3-11/scripts/10_op-sdk-setup.sh

@BenHall This should now be correct.  My bad for missing these in my testing.  Thanks again for your help.

Fixing typos in operator-sdk installation script for 3.11 env

---

operatorframework/operator-lifecycle-manager/step1.md

When deploying Operator Lifecycle Manager via Kubernetes manifests, avoid possible race condition on slower systems by creating creating OLM objects in separate steps.

Modify deployment of Operator-Lifecycle-Manager manifests

---

operatorframework/k8s-api-fundamentals/step3.md

Specify myproject namespace when initially listing pods on ReplicaSet exercise.

Specify myproject namespace when initially listing pods 

---

operatorframework/go-operator-podset/step2.md
operatorframework/go-operator-podset/step5.md
operatorframework/go-operator-podset/step6.md

fix various typos in operator-sdk (go-based) module

fix various typos in operator-sdk (go-based) module

---

operatorframework/go-operator-podset/env-init.sh

`dep` does not show up in the operator-sdk (go-based) module environment, although it's set in the environment script: https://github.com/openshift-labs/learn-katacoda/blob/master/environments/openshift-3-11/scripts/10_op-sdk-setup.sh#L28
As a workaround, add it to `env-init.sh`.

Add dep install to operator-sdk (go-based) module

---

operatorframework/go-operator-podset/env-init.sh
operatorframework/go-operator-podset/set-env.sh

Although #329 was merged - I am still not seeing `dep` installed in the environment.
As a temporary workaround (like the operator-sdk install), I've added it to set-env.sh.
Thanks!

Dep missing from go-operator-podset environment

---

operatorframework/etcd-operator/step1.md
operatorframework/go-operator-podset/step2.md

remove verification of new CRD `Kind:` via `oc`. The ` No resources found` output seems to be confusing to some participants.

remove verification of new resource check via cli

---

ansibleop/ansible-operator-overview/step5.md

The `operator-sdk new` command will by default attempt to initialize a git repo. Since user info
has not been configured for git in the learning environment, this causes an error. The solution is to
use the --skip-git-init flag. This was accidentally removed in https://github.com/openshift-labs/learn-katacoda/pull/337.

adds --skip-git-init, which was accidentally removed in a prior change

---

operatorframework/go-operator-podset/step5.md

operator-sdk v0.3.0+ automatically sets status subresource on CRD - use StatusWriter (client.Status().Update) to publish podNames status (instead of client.Update).
@marekjelen  @BenHall

Use StatusWriter to Update podNames status

---

introduction/getting-started/4scaling.md

This pull request aims to add a minor language update to the `Step 4 - Scaling Your Application` section of the `Getting Started with OpenShift for Developers` tutorial.
As part of going through the `Getting Started with OpenShift for Developers` tutorial my first time, I actually wanted to navigate back to the `Overview` screen of my project before moving on to the `Application "Self Healing"` portion of the section. This caused me to not see the `Actions` tab when moving forward in the tutorial and led to some minor confusion. 
I propose adding some simple language to the tutorial to assure the user knows how to find the `Actions` tab to delete the pod to illustrate OpenShift's self healing capabilities.

Add Page Location Language to Getting Started Tutorial

---

operatorframework/go-operator-podset/finish.md

This is a Go-based tutorial and not an Ansible tutorial and so it should refer to itself accordingly.
See issue #379 for more details and the topic of whether or not later Ansible references are desired for this Go tutorial.

Correctly refer to the tutorial by Go (not Ansible)

---

ansibleop/ansible-operator-overview/env-init.sh

Ansible-Operator exercise should allow you to build and deploy operator via admin user. Prevent removal of .kube/config file in environment initialization.

Do not remove admin .kube/config upon environment initalization

---

ansibleop/ansible-operator-overview/step7.md
ansibleop/ansible-operator-overview/step8.md

Now that the system:admin .kube/config file remains, remove logging in as 'developer' user and perform all actions as system:admin for simple user experience.

Remove logging in as 'developer' user

---

operatorframework-pathway.json
operatorframework/go-operator-podset/index.json

For module title uniformity, Remove "Podset" from "Operator SDK with Go" title

Remove Podset from "Operator SDK with Go" title

---

introduction/developing-with-odo/set-env.sh

This pull request is a temporary way to address #472. This will set up the tutorial environment with the correct version of `odo` needed for the tutorial. This does not fully address #472 as the ideal solution will be to not have to install `odo` each time the scenario is launched, but it will temporarily fix the scenario for users.

Adding Download of odo v1.0.0-beta2 to Fix Odo Tutorial

---

introduction/developing-with-odo/set-env.sh

Closes #472 
This pull request removes the installation of `odo v1.0.0-beta2` for the `Developing with odo` tutorial. The issue with #472 was that there was a hardcoded in workaround that had been used for helping upgrade the tutorial to `odo v0.0.17` that was not allowing the new version of `odo` to be used. This workaround has been removed, so it will no longer override the binary in the OpenShift 3.11 image used for the tutorial. The OpenShift 3.11 image now has `odo v1.0.0-beta2` correctly installed.

Removing odo v1.0.0-beta2 Download

---

introduction/developing-with-odo/04-linking-components.md
introduction/developing-with-odo/05-exposing-components-to-public.md
introduction/developing-with-odo/set-env.sh

This pull request corrects information in the content for the `Developing with odo` tutorial. Currently, the tutorial states that linking components is not finished via `odo` until an `odo push` occurs. However, running `odo link backend --component frontend --port 8080` does not require an `odo push` to link the components in the scenario. The `frontend` component is restarted with the linking information after running `odo link backend --component frontend --port 8080`.

Update Linking Components Content for Developing with odo

---

introduction/developing-with-odo/set-env.sh

`odo utils config set UpdateNotification false` is no longer the way to suppress a version update warning with `odo`. This has been changed to `odo preference set UpdateNotification false`. 
For more information on this, please view the `odo` issues I opened [here](https://github.com/openshift/odo/issues/1835).

Update odo utils config to odo preference to Suppress Version Update Warning

---

introduction/using-metrics/2sample-application.md

The kubernetes/guestbook image has been deprecated it seems.
Fixes #479 & #453

Use the cached image as it has been deprecated

---

middleware/rhoar-getting-started-nodejs/03-deploy-to-openshift.md
middleware/rhoar-getting-started-nodejs/05-add-logic-for-retrieving-configmaps.md
middleware/rhoar-getting-started-nodejs/07-redeploy-to-openshift.md

Running "nodeshift" will give the message "complete", not "done"
Changed the way the text was structured in the `oc rollout` part to make it less confusing (command, then output)

Fixed typos and text

---

subsystems/container-internals-lab-2-0-part-7/01-podman.md

In lab 7 
for the commands: "podman stop / rm / rmi" the flag should be "--all" not "-all".
And there were typos that I have fixed. 
I kinda like this contributing thing but I want to do it over code. Any suggestions?

Fix flags and typos in lab7 part1

---

subsystems/container-internals-lab-2-0-part-1/04-hosts.md

Without the extra newline, there's no whitespace between the commands and at a glance it gives the impression that they're not separate commands:
> ![container-internals-20-lab1-step4](https://user-images.githubusercontent.com/346123/57468727-0e57d500-7253-11e9-8201-6d71cfe8839a.png)

Make it more clear the commands are separate

---

ansibleop/ansible-operator-overview/step9.md

These were leftover from a previous version of the exercise but are no
longer needed.

removes unnecessary --as system:admin flag

---

environments/openshift-3-11/scripts/12_quarkus-setup.sh
middleware/middleware-quarkus/getting-started/01-create-project.md
middleware/middleware-quarkus/getting-started/04-build-native.md
middleware/middleware-quarkus/getting-started/05-deploy-to-openshift.md
middleware/middleware-quarkus/getting-started/set-env.sh
middleware/middleware-quarkus/panache/01-define-entity.md

@BenHall - this PR updates the `environments/openshift-3-11` scripts to use the latest Quarkus and GraalVM. The base `openshift-3-11` image will need to be rebuilt and put into prod before this code can be merged. Happy to test things out if you can re-build in a non-prod environment.

Update to Quarkus 0.21.1

---

introduction/using-metrics/2sample-application.md

Error occurring previous to this change when running the new-app stage is shown as below.
$ oc new-app kubernetes/guestbook
error: Errors occurred while determining argument types:
kubernetes/guestbook as a local directory pointing to a Git repository:  stat kubernetes/guestbook: no such file or directory
Errors occurred during resource creation:
error: only a partial match was found for "kubernetes/guestbook": "docker.io/kubernetes/guestbook:latest"
The argument "kubernetes/guestbook" only partially matched the following Docker image, OpenShift image stream, or template:
* Docker image "docker.io/kubernetes/guestbook:latest", 7dc61f8, from local, 11.827mb
Use --docker-image="docker.io/kubernetes/guestbook:latest" to specify this image or template

Fix partial match docker image

---

middleware/middleware-quarkus/kafka/06-deploy-kafka.md

If the user does not execute the "hello" test command on step1 (that also does a "cd" command), he will not be able to execute step 6.
Therefore, I added a preventive step to avoid unexpected errors from end-users on step 6.

Adding a preventive fix step, to quarkus with kafka course, step6

---

servicemesh/4-simple-routerules/1modify-recommendation.md
servicemesh/8-egress/1create-recommendation-v3.md
servicemesh/8-egress/2istioize-egress.md
servicemesh/adv2-mTLS/1before-start.md

Just going through these workshops. Minor changes detailed below. ~, but I don't get a pager when checking the `git diff` so I think we can remove this piece here. Not sure if the pager was in place previously and the behavior changed.~
EDIT: Adding a typo fix to this branch so relabeling title and this post for clarity.
`remove q to exit git diff pager` Fixes:
*  Removes a command to exit the git diff pager where a pager does not come up in 2 files.
`fixing a typo` Fixes:
*  a typo _reccomendation_ to _recommendation_ in 1 file.
* a typo _Applye_ to _Apply_ in 1 file.
`update tasks to replace now.httpbin.org with worldclockapi.com` Fixes #612 
`add preformatted text markers for clarity` fixes
* a section in adv2-mtls/1before-start.md which represents output but was not enclosed in …

Remove extra commands, fix typos

---

subsystems/container-internals-lab-2-0-part-7/01-podman.md

Seems like the registry of Fedora isn't offering the f28 anymore ... tested with f29 worked

URL fix for fedora-toolbox

---

environments/openshift-4-2/master/build/5_odh-pull.sh

This should pre-pull required images by the odh operator to improve the environment set up times.

[env/4.2] pre-pull image OpenDataHub Operator Image

---

homepage-pathway.json
operatorframework-pathway.json
servicemesh-pathway.json
subsystems-pathway.json

This set contains simple category and scenario renaming for consistency.
Future changes will be more invasive in terms of reorganizing
categories and creating new  ones.
These changes include renaming for consistency for:
- the operators category name
- the Linux Container Fundamentals (formerly "Subsystems...") category
- the Istio (formerly "Service Mesh") category

[WIP] First pass at 2020 reorg

---

introduction/deploy-prometheus-grafana/index.json
introduction/deploy-prometheus-grafana/set-env.sh

It seems like the index.json asset file spec doesn't like the
trailing slash on ~ or other target directories. This actually
resolved the missing `deploy-prometheus.yaml`.
Also s/host01/client/ to match other scenarios' asset file specs.(?)
Fixes #820
Fixes #817 
Fixes #800

index.json and set-env.sh: Fix file spec for deploy-prometheus.yaml

---

middleware/fuse-hello-world/intro.md

The link to the Hello World has changed due to publishing template changes on the RHD site. Also, the instructions for the prerequisites needed improvement as the reader must acquire Red Hat's CodeReady Studio before they can do the tutorial.

Fix links to Hello World for the Fuse katacoda

---

subsystems/container-internals-lab-2-0-part-5/01-multi-container-applications.md
subsystems/container-internals-lab-2-0-part-5/02-load-testing.md
subsystems/container-internals-lab-2-0-part-5/03-troubleshooting-distributed-applications.md

Relates to issue #577
Fixes incorrect awk commands. Currently isolates the type, i.e. ClusterIp, LoadBalance, instead of returning the cluster ip.

Fix: awk instruction for oc get svc

---

branded-ui/katacoda/redirect.go

Please try this to create the redirect for https://learn.openshift.com/operators to
https://learn.openshift.com/operatorframework.
This is in response to a request to the Katacoda support team.

Redirect /operators to /operatorframework

---

redirect.json

This is an additional setting needed for the redirect to work.

Set redirect from /operators to /operatorframework

---

cicd-application-delivery-pathway.json
redirect.json

the "redirect" method worked on my personal katacoda, but not learn., so maybe something else is going on.  just copied the GitOps.json over to cicd-app-delivery

redirect cicd app delivery to gitops

---

operatorframework/etcd-operator/finish.md
operatorframework/etcd-operator/index.json
operatorframework/etcd-operator/intro.md
operatorframework/go-operator-podset/index.json
operatorframework/helm-operator/index.json
operatorframework/operator-lifecycle-manager/index.json

Upgrade to OpenShift 4.7 (#1142) and work on formatting standardization

etcd to 4-7

---

middleware-pathway.json
middleware/middleware-javaee8/index.json

Updated to `openshift-4-7`:
related: #1060

bump JavaEE8 from 4-6 to 4-7

---

branded-ui/katacoda/templates/banner.html

Changed the "Report an Issue" link to bring users to the template selection page instead of directly to an empty report. Hopefully this provides more consistency in the quality of our bug reports.

Updated the report an issue link

---

operatorframework/go-operator-memcached/env-init.sh

Temporary solution for #1205 to reinstall the Operator SDK to the latest version to allow for `init` command to be used

Updating env-init.sh to fix go memcached issue

---

operatorframework/etcd-operator/index.json

Update etcd exercise to  openshift-4-7 to resolve exec and logs errors that are showing up on openshift-4-5 image

Update etcd exercise to  openshift-4-7

---

ansibleop/ansible-k8s-modules/index.json
ansibleop/ansible-mcrouter-operator/index.json
ansibleop/ansible-operator-overview/index.json
operatorframework/go-operator-podset/assets/podset_controller.go
operatorframework/go-operator-podset/index.json
operatorframework/go-operator-podset/step4.md
operatorframework/helm-operator/index.json
operatorframework/helm-operator/step4.md
operatorframework/k8s-api-fundamentals/index.json
operatorframework/operator-lifecycle-manager/index.json

Updates all operator exercises to openshift-4-7 image which should eliminate #1288, #1286, #1285, #1284, #1282, #1277, #1276, #1275

update op framework exercises to 4.7
