openshift-labs/learn-katacoda

branded-ui/katacoda/content/introduction/getting-started.html
branded-ui/katacoda/content/katacoda-introduction/application-healthchecks.html
branded-ui/katacoda/content/katacoda-introduction/build-docker-images.html
branded-ui/katacoda/content/katacoda-introduction/deploy-containers-using-cli.html
branded-ui/katacoda/content/katacoda-introduction/deploy-containers-using-ui.html
branded-ui/katacoda/content/katacoda-introduction/install-deploy-openshift.html
branded-ui/katacoda/content/katacoda-introduction/nfs-server.html
branded-ui/katacoda/content/katacoda-introduction/playground.html
branded-ui/katacoda/layouts/index.html
branded-ui/katacoda/layouts/indexes/introduction.html
branded-ui/katacoda/layouts/indexes/katacoda-introduction.html

@gshipley @thesteve0 Please merge

Adds brand colors and fonts to course pages

---

intro-openshift/asp-net/assets/route.json
intro-openshift/asp-net/env-init.sh
intro-openshift/asp-net/index.json
intro-openshift/cluster-access/assets/route.json
intro-openshift/cluster-access/env-init.sh
intro-openshift/cluster-access/index.json
intro-openshift/deploying-images/assets/route.json
intro-openshift/deploying-images/env-init.sh
intro-openshift/deploying-images/index.json
intro-openshift/getting-started/assets/route.json
intro-openshift/getting-started/env-init.sh
intro-openshift/getting-started/index.json
intro-openshift/resource-objects/assets/route.json
intro-openshift/resource-objects/env-init.sh
intro-openshift/resource-objects/index.json

Move to new Assets structure

---

branded-ui/katacoda/content/introduction/port-forwarding.html
intro-openshift-pathway.json
intro-openshift/port-forwarding/01-creating-an-initial-project.md
intro-openshift/port-forwarding/02-deploying-a-postgresql-database.md
intro-openshift/port-forwarding/03-connecting-to-the-database.md
intro-openshift/port-forwarding/03-starting-an-interactive-shell.md
intro-openshift/port-forwarding/04-creating-a-remote-connection.md
intro-openshift/port-forwarding/env-init.sh
intro-openshift/port-forwarding/finish.md
intro-openshift/port-forwarding/index.json
intro-openshift/port-forwarding/intro.md
intro-openshift/port-forwarding/set-env.sh

Preview at:
* https://katacoda.com/graham.dumpleton/courses/intro-openshift/port-forwarding

Add scenario on port forwarding.

---

branded-ui/katacoda/layouts/partials/header.html
branded-ui/katacoda/static/container-platform.css

Signed-off-by: Will Gordon <wgordon@redhat.com>

Add Report an Issue button

---

intro-openshift/fis-deploy-app/01-creating-an-initial-project.md
intro-openshift/fis-deploy-app/02-deploying-first-fuse-application-on-openshift.md
intro-openshift/fis-deploy-app/04-exceute-the-apis.md
intro-openshift/fis-deploy-app/finish.md

- respect GitHub camelcase
- fix typos
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Fix several typos

---

environments/openshift-middleware/scripts/populate-maven-repos.sh

@BenHall What about this pull request instead?

Added logging to the populate-maven-repos.sh script

---

environments/openshift-middleware/scripts/populate-maven-repos.sh

- Fixed issue with wrong verison of spring-boot plugin.
- Changed so that if a solution branch is available we also build using it.

Updated the populate-maven-repos.sh

---

environments/openshift-middleware-3-7/scripts/middleware-pull.sh
environments/openshift-middleware-3-7/scripts/populate-maven-repos.sh

@mhausenblas I need these resources pre-fetched to be used in the istio-tutorial. Can you merge it please?

Added resources needed by istio-tutorial

---

environments/openshift-3-6-metrics/openshift-metrics.json
environments/openshift-3-6-metrics/scripts/metrics.sh
introduction/using-metrics/index.json
introduction/using-metrics/set-env.sh

Fixes for the metrics scenario

---

environments/openshift-middleware-3-7/scripts/istio-pull.sh

ServiceGraph 0.5.0 contains a bug ( https://github.com/istio/istio/issues/3015 ) so we need to user servicegrah 0.4.0 here. I've also add Grafana

Added Grafana and Servicegraph 0.4.0

---

introduction-pathway.json
introduction/using-metrics/3create-hpa.md

I've tested it and it works properly. This PR will make the scenario go live in the learn.openshift.com site.
Thanks!!!

Make the using metrics scenario live

---

environments/openshift-middleware/scripts/middleware-pull.sh

RHDM7 images are required for the new scenario's for Red Hat Decision Manager 7.

Added the images of Red Hat Decision Manager 7.

---

middleware/resilient-apps/04-routing.md
middleware/resilient-apps/07-circuit-breaking.md
middleware/resilient-apps/assets/install-istio.sh
middleware/resilient-apps/assets/install-sample-app.sh

Please review and merge @BenHall

update to istio 0.6.0 in resilent-apps scenario

---

homepage-pathway.json
servicemesh-pathway.json
servicemesh/2-deploy-microservices/index.json
servicemesh/3-monitoring-tracing/3tracing.md
servicemesh/3-monitoring-tracing/index.json
servicemesh/4-simple-routerules/index.json
servicemesh/5-advanced-routerules/index.json
servicemesh/6-fault-injection/index.json
servicemesh/7-circuit-breaker/index.json
servicemesh/8-egress/index.json

@BenHall @mhausenblas Can you merge, please? thank you

Add Servicemesh to homepage and fix istio scenarios and titles

---

middleware/debezium-getting-started/00-intro.md

Fix for https://github.com/openshift-labs/learn-katacoda/issues/167

Fix Debezium deployment URL

---

servicemesh/4-simple-routerules/run-init.sh

@mhausenblas Please, merge this as I missed this detail on PR #169

Missed one file on new folder structure on PR #169

---

branded-ui/katacoda/templates/banner.html
branded-ui/katacoda/templates/footer.html
branded-ui/katacoda/templates/header.html

DO NOT MERGE until after 1pm EST on May 3.

Update site nav with openshift.com redesign

---

serverless-pathway.json
serverless/3-web-accessible-actions/01-create-java-function.md
serverless/3-web-accessible-actions/assets/setup-environment.sh
serverless/3-web-accessible-actions/index.json
serverless/4-chained-actions/01-create-package.md
serverless/4-chained-actions/02-create-split-function.md
serverless/4-chained-actions/03-create-sort-function.md
serverless/4-chained-actions/04-create-uppercase-function.md
serverless/4-chained-actions/assets/setup-environment.sh
serverless/6-packages/00-intro.md
serverless/6-packages/01-getting-started.md
serverless/6-packages/02-adding-functions.md
serverless/6-packages/03-parameters.md
serverless/6-packages/04-more-parameters.md
serverless/6-packages/05-sharing.md
serverless/6-packages/99-outro.md
serverless/6-packages/assets/setup-environment.sh
serverless/6-packages/index.json
serverless/6-packages/set-env.sh
serverless/6-packages/test.sh

and some updates/fixes to a couple of other scenarios

add a new package scenario

---

servicemesh/2-deploy-microservices/4deploy-preference.md
servicemesh/3-monitoring-tracing/run-init.sh
servicemesh/4-simple-routerules/run-init.sh
servicemesh/5-advanced-routerules/assets/install-microservices.sh
servicemesh/6-fault-injection/assets/install-microservices.sh
servicemesh/7-circuit-breaker/assets/install-microservices.sh

Update to match https://github.com/redhat-developer-demos/istio-tutorial/pull/74

Fix for https://learn.openshift.com/servicemesh due to a new PR

---

servicemesh/5-advanced-routerules/1useragent-routing.md

Related to https://github.com/redhat-developer-demos/istio-tutorial/pull/81#issuecomment-396527538 
cc @rafabene

Update user-agent routing to use baggage

---

middleware/dm7-loan-application/env-init.sh
middleware/dm7-loan-application/stateless-kie-session.md

Increases timeout of the haproxy for Decision Central routes in Decision Manager 7 Loan Application Scenario.

Dm7 loan application increase timeout

---

servicemesh/1-introduction/3installation.md
servicemesh/3-monitoring-tracing/2custom-metric.md
servicemesh/4-simple-routerules/1modify-recommendation.md
servicemesh/4-simple-routerules/2all-usersv2.md
servicemesh/4-simple-routerules/4all-usersv12.md
servicemesh/4-simple-routerules/5canary-deployment.md

@BenHall @mhausenblas One more, please. Maybe I should have access to this repo to increase the pace of fixing things.

Add external routes

---

servicemesh/1-introduction/3installation.md
servicemesh/3-monitoring-tracing/2custom-metric.md
servicemesh/4-simple-routerules/1modify-recommendation.md
servicemesh/5-advanced-routerules/0install-microservices.md
servicemesh/5-advanced-routerules/1useragent-routing.md
servicemesh/5-advanced-routerules/2dark-launch.md
servicemesh/5-advanced-routerules/assets/install-microservices.sh
servicemesh/6-fault-injection/0install-microservices.md
servicemesh/6-fault-injection/1http-error-503.md
servicemesh/6-fault-injection/assets/install-microservices.sh
servicemesh/7-circuit-breaker/0install-microservices.md
servicemesh/7-circuit-breaker/2fail-fast.md
servicemesh/7-circuit-breaker/3pool-ejection.md
servicemesh/7-circuit-breaker/4ultimate-resilience.md
servicemesh/7-circuit-breaker/assets/install-microservices.sh

@BenHall and @mhausenblas Minor fixes.

Minor fixes

---

servicemesh/5-advanced-routerules/2dark-launch.md

@BenHall @mhausenblas Missed a semicolon

Ops. Missed a semicolon

---

servicemesh/5-advanced-routerules/assets/install-microservices.sh
servicemesh/6-fault-injection/assets/install-microservices.sh
servicemesh/7-circuit-breaker/assets/install-microservices.sh

@BenHall @mhausenblas Improvements please.

Better error messages in the scripts

---

training/container-internals-pathway.json

Testing change to use my fork

---

environments/openshift-3-11/scripts/9_odo.sh

- Add command to download and install odo within bash script
- Fix #263

Add command to download and install odo

---

servicemesh/6-fault-injection/2delay.md

Please merge it @mhausenblas cc @BenHall @burrsutter

Fix Delay Step of Scenario 6

---

environments/openshift-3-11/scripts/9_odo.sh

- Use a versioned release of odo instead of latest

Use a versioned release of odo instead of latest

---

environments/openshift-3-11/scripts/9_odo.sh

Bumping the version of odo to 0.0.17 so that users won't get an upgrade warning.

Updating odo to version 0.0.17

---

subsystems/container-internals-lab-2-0-part-2/03-image-internals.md
subsystems/container-internals-lab-2/03-image-internals.md

Thanks for creating the training material! Just one small typo noticed.

Fix typo of openssl.

---

subsystems/container-internals-lab-2-0-part-5/01-multi-container-applications.md

Update 01-multi-container-applications.md - fixed several typos

---

ansibleop/ansible-operator-overview/assets/op-sdk-setup.sh
environments/openshift-3-11/scripts/10_op-sdk-setup.sh

@BenHall @mhausenblas  - This needs to get merged before you cut a new 3.11 image.  Thanks.

Moving operator-sdk binary into proper directory.

---

operatorframework/go-operator-podset/index.json
operatorframework/go-operator-podset/set-env.sh
operatorframework/go-operator-podset/step5.md
operatorframework/go-operator-podset/step7.md
operatorframework/operator-lifecycle-manager/step1.md

Add updated PodSet reconciler logic for PodSet example.

Add updated PodSet reconciler logic

---

ansibleop/ansible-operator-overview/set-env.sh

temporary set-env script fix for workshop
tsanders has already made these changes in the base image, so these should be removed after the workshop.

temporary set-env script fix for workshop

---

ansibleop/operator-sdk-playground/env-init.sh
homepage-pathway.json
operatorframework-pathway.json

Combining Operator Development Courses and making available on top-level

---

operatorframework/operator-lifecycle-manager/step3.md

Add creation of `myproject` namespace to OLM step3

Add creation of `my project` namespace to OLM step3

---

operatorframework/etcd-operator/step3.md
operatorframework/etcd-operator/step7.md

remove jsonpath typo when getting the Etcd operator pod name

remove jsonpath typo when getting the Etcd operator pod name

---

operatorframework/etcd-operator/step5.md

replace `kubectl exec` command with `oc rsh`

replace `kubectl exec` command with `oc rsh`

---

operatorframework/etcd-operator/step4.md

Refine wording when creating the EtcdCluster Custom Resource

Refine wording when creating the EtcdCluster Custom Resource

---

operatorframework/etcd-operator/intro.md

Fix broken etcd-operator hyperlinks

Fix broken etcd-operator hyperlinks

---

middleware/fuse-hello-world/finish.md

Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>

middleware/fuse-hello-world - update links to the latest version 7.2

---

operatorframework/etcd-operator/step8.md

change kubectl to oc for consistency

change kubectl to oc for consistency

---

ansibleop/ansible-k8s-modules/intro.md
ansibleop/ansible-k8s-modules/step1.md
ansibleop/ansible-k8s-modules/step2.md

Revisions to ansible-k8s-module aimed at providing enhanced readability and clarity.
- Add alphabet labeled sub-steps within scenario steps, separated by horizontal rules
- Create additional explanation on some steps

ansible-k8s-module revision

---

ansibleop/ansible-k8s-modules/step2.md
ansibleop/ansible-k8s-modules/step3.md
ansibleop/ansible-operator-overview/step4.md

ansibleop scenario fixes

---

ansibleop/ansible-k8s-modules/index.json
ansibleop/ansible-operator-overview/step2.md
ansibleop/ansible-operator-overview/step4.md
ansibleop/ansible-operator-overview/step7.md
ansibleop/ansible-operator-overview/step8.md
ansibleop/ansible-operator-overview/step9.md

Fixes for ansible-operator-overview scenario

---

external/citrus/intro/env-init.sh
external/citrus/intro/finish.md
external/citrus/intro/index.json
external/citrus/intro/install-java-mvn.sh
external/citrus/intro/intro.md
external/citrus/intro/set-env.sh
external/citrus/intro/step0.md
external/citrus/intro/step1-verify.sh
external/citrus/intro/step1.md
external/citrus/intro/step2-setup.sh
external/citrus/intro/step2.md
external/citrus/intro/step3.md
external/citrus/intro/step4-setup.sh
external/citrus/intro/step4.md
external/citrus/intro/step5.md

This introduces a basic introduction to on integration testing with citrus framework in the (new) external section. The System under test is currently deployed in an external openshift cluster.

add citrus basic (http) tutorial setup

---

external-pathway.json
external/citrus-pathway.json

fix #353 add pathway links

---

operatorframework/operator-lifecycle-manager/step2.md

Update origin-console container image tag to use v3.11.0.
@marekjelen  @BenHall

Update origin-console container image tag

---

environments/openshift-3-11/scripts/12_quarkus-setup.sh
environments/openshift-3-11/scripts/1_configure-java.sh

Adds prereqs for building java apps with Quarkus

Add dependencies for Quarkus

---

middleware/debezium-getting-started/01-deploying-a-broker.md

Follow up to https://github.com/openshift-labs/learn-katacoda/issues/162#issuecomment-381983007

Note about startup time

---

operatorframework-pathway.json

Remove operator-sdk-playground module

Remove operator-sdk-playground module

---

introduction/federated-clusters/02-deploying-federation-control-plane.md
introduction/federated-clusters/03-registering-clusters-into-the-cluster-registry.md
introduction/federated-clusters/04-deploying-a-federated-app.md
introduction/federated-clusters/05-federation-objects.md
introduction/federated-clusters/06-modifying-application-placement.md
introduction/federated-clusters/set-env.sh

This PR updates the federation scenario so it uses the latest federation-v2 release.

Updated scenario to v0.0.7 spec

---

operatorframework-pathway.json
operatorframework/helm-operator/assets/.init.sh
operatorframework/helm-operator/env-init.sh
operatorframework/helm-operator/finish.md
operatorframework/helm-operator/index.json
operatorframework/helm-operator/intro.md
operatorframework/helm-operator/set-env.sh
operatorframework/helm-operator/step1.md
operatorframework/helm-operator/step2.md
operatorframework/helm-operator/step3.md
operatorframework/helm-operator/step4.md
operatorframework/helm-operator/step5.md
operatorframework/helm-operator/step6.md
operatorframework/helm-operator/step7.md
operatorframework/helm-operator/step8.md
operatorframework/helm-operator/step9.md

Add Helm Operator Module to Operator Framework

Add Helm Operator Module to Operator Framework

---

operatorframework/helm-operator/step2.md
operatorframework/helm-operator/step4.md
operatorframework/helm-operator/step8.md

- Correct typos in paths to files to be updated
- Set variable for cockroachdb service prior to connection

Fix a few typos with Helm module

---

operatorframework/helm-operator/set-env.sh
operatorframework/helm-operator/step1.md
operatorframework/helm-operator/step2.md
operatorframework/helm-operator/step3.md
operatorframework/helm-operator/step4.md

Update Helm Operator exercise to support easy fetch of existing chart via --helm-chart and --helm-cart-repo flags

Update Helm Operator exercise to support easy fetch of existing chart

---

ansibleop/ansible-operator-overview/step7.md

Operator SDK `0.6.0` sets values with new format in operator.yaml. Update sed commands to find these values.

update sed commands to find latest default values in operator.yaml

---

branded-ui/katacoda/templates/header.html

Updating GTM ID because it was using an outdated one.

Update GTM ID

---

operatorframework/operator-lifecycle-manager/step1.md

Upstream OLM repo recently removed okd directory. Update exercises to use ocp.

Update manifests path to reflect okd-->ocp

---

branded-ui/katacoda/templates/footer.html
branded-ui/katacoda/templates/header.html

Please let me know once these changes get deployed. Thanks!

Added adobe tag manager to header and footer

---

introduction/deploying-images/04-deleting-the-application.md

Corrects "oc get" output when resource is empty

---

operatorframework/helm-operator/step4.md
operatorframework/helm-operator/step7.md
operatorframework/helm-operator/step8.md

@BenHall Trying to get this merged before our scheduled Operator Workshop on 7/17.
Thank you!

 bump cockroachdb helm chart from v2.1 to v2.1.11

---

subsystems/container-internals-lab-2-0-part-5/foreground.sh

Fixed git clone which was breaking lab #5

SM: added new git clone command

---

middleware/fuse-hello-world/02-deploying-first-fuse-application-on-openshift.md
middleware/fuse-hello-world/finish.md

Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>

middleware/fuse-hello-world - update links to the latest version 7.4

---

operatorframework/etcd-operator/step1.md
operatorframework/go-operator-podset/intro.md
operatorframework/go-operator-podset/step1.md
operatorframework/go-operator-podset/step3.md

fixes minor typos

---

subsystems/container-internals-lab-2-0-part-3/foreground.sh
subsystems/container-internals-lab-2-0-part-4/02-create-container.md
subsystems/container-internals-lab-2-0-part-4/foreground.sh
subsystems/container-internals-lab-2-0-part-5/foreground.sh
subsystems/container-internals-lab-2-0-part-6/env-init.sh
subsystems/container-internals-lab-2-0-part-7/env-init.sh

* Fixed race condition in pre-provisioned environments with cp command
* Fixed storage problem showing wrong out put with docker/podman

Fixed small race condition and storage problem

---

environments/openshift-3-11/scripts/12_quarkus-setup.sh
environments/openshift-3-11/scripts/4_middleware-pull.sh
middleware/middleware-quarkus/getting-started/01-create-project.md
middleware/middleware-quarkus/getting-started/05-deploy-to-openshift.md
middleware/middleware-quarkus/monitoring/02-create-and-instrument-app.md

@BenHall this updates to the latest Quarkus release, including changes in the `/environments` directory in the repo. Please re-build the base image and test out the 'getting started' scenario with the updated code in a non-production environment. If it works then please update the production environment with the new environment image (with the Quarkus 0.22.0 artifacts). Thanks!

Update to Quarkus 0.22.0

---

ansibleop/ansible-operator-overview/step1.md

remove an unnecessary "with" from line 23

 fix minor typo in ansibleop/ansible-operator-overview/step1.md

---

environments/openshift-3-11/scripts/11_middleware.sh
middleware/debezium-getting-started/00-intro.md
middleware/debezium-getting-started/01-deploying-a-broker.md
middleware/debezium-getting-started/02-deploying-a-kafka-connect.md
middleware/debezium-getting-started/03-streaming-data-from-database.md
middleware/debezium-getting-started/assets/register.json
middleware/debezium-getting-started/assets/setup-openshift.sh
middleware/debezium-getting-started/index.json
middleware/debezium-getting-started/run-init.sh
middleware/debezium-getting-started/set-env.sh

Implementation of https://trello.com/c/9Qjkw50V/86-upgrade-debezium-demo-to-the-latest-version-of-debezium-and-strimzi

Upgrade to Debezium 0.10 and Strimzi 0.14

---

environments/openshift-3-11/scripts/12_quarkus-setup.sh
middleware/middleware-quarkus/getting-started/01-create-project.md
middleware/middleware-quarkus/monitoring/02-create-and-instrument-app.md
middleware/middleware-quarkus/spring/01-create-project.md

@BenHall this updates to latest Quarkus release. Please review and re-build base image (to cache the maven artifacts) and if you can step through the first getting-started scenario then please push to prod. thanks!

Update to Quarkus latest

---

operatorframework/helm-operator/step4.md
operatorframework/helm-operator/step7.md
operatorframework/helm-operator/step8.md

update cockroach db helm exercise to support latest cockroachdb chart's `values.yaml`

update helm exercise to support latest cockroachdb chart

---

subsystems/container-internals-lab-2-0-part-5/01-multi-container-applications.md
subsystems/container-internals-lab-2-0-part-5/foreground.sh

Add admin to default project and fix link

---

ai-machine-learning/jupyterhub-workspace/env-init.sh

Fixes https://github.com/openshift-labs/learn-katacoda/issues/662

Update image stream version

---

environments/openshift-4-2/client/build/3_op-sdk-setup.sh

@BenHall thanks for all your help!

update operator-sdk build script for openshift-4.2 image

---

environments/openshift-4-2/client/build/1_packages.sh

This PR add Kogito and CamelK binaries for the 4.2 client machine.

add camelK and Kogito binaries for client

---

operatorframework/operator-lifecycle-manager/finish.md
operatorframework/operator-lifecycle-manager/intro.md

This PR fixes the issue #688 
@BenHall, could you please review this? Thanks!

Fix incorrect hyperlinks for OLM scenario

---

introduction/cluster-access/intro.md
introduction/deploying-images/intro.md
introduction/developing-with-odo/intro.md
introduction/getting-started/intro.md

Standardize format of the intro page of 4 sample scenarios to make them more concise and improve stickiness of intro -> step1 transitions.
Standard format based on https://lab.redhat.com/imagebuilder

introduction/*/intro.md: Standardize the format of intro.md

---

middleware/amq-getting-started-broker/index.json

Fix amq broker

---

middleware/debezium-getting-started/02-deploying-a-kafka-connect.md

updated maven location and upgraded the connector version.

fix maven download

---

persistence/persistent-elasticsearch/03.md
persistence/persistent-elasticsearch/04.md

With this PR I am submitting minor instruction changes to persistence/persistent-elasticsearch scenario.  I would appreciate, if you can merge this before this goes live today. Thanks

minor instruction changes

---

ansibleop/ansible-k8s-modules/finish.md
ansibleop/ansible-k8s-modules/step3.md
ansibleop/ansible-operator-overview/step8.md

This PR correct a few typos found in Ansible Operator exercises.

Fix typos on Ansible Operator Exercises

---

middleware/middleware-vertx/getting-started-vertx/01-local-build.md
middleware/middleware-vertx/getting-started-vertx/04-deploy-to-openshift.md

Getting started scenario changed according to the rhoar-getting-started upgrade to 3.9

upgrade to vertx 3.9

---

introduction/getting-started/6s2i.md

I came across the old, broken link when viewing the content.

Update old S2I link with one that works

---

developing-on-openshift-pathway.json
developing-with-kogito-pathway.json
developing-with-quarkus-pathway.json
developing-with-spring-pathway.json
developing-with-vertx-pathway.json
enterprise-java-pathway.json
homepage-pathway.json

- Removed "Middleware" and replaced with multiple top level categories
- Reordered homepage accordingly
Changes are currently live on https://katacoda.com/jdob

learn.openshift.com top level reorg - phase 2

---

playgrounds/openshift311/intro.md
playgrounds/openshift42/intro.md
playgrounds/openshift44/intro.md

playgrounds/: Standard intros for version 3.11-4.4

---

introduction/cluster-access/finish.md
introduction/deploying-images/finish.md
introduction/deploying-python/finish.md
introduction/developing-with-odo/finish.md
introduction/getting-started/finish.md
introduction/port-forwarding/finish.md
introduction/resource-objects/finish.md
introduction/transferring-files/finish.md

This will establish a tracking baseline for us to measure against.

Add URL params to the CTA URLs for some intro scenarios

---

introduction/gitops-multicluster/04-customize-app-deployment.md

Fixes #804. (in combination with tuning on kc side)

intro/gitops-multi/04: Add note about file delay.

---

operatorframework/k8s-api-fundamentals/step3.md
operatorframework/k8s-api-fundamentals/step4.md
operatorframework/operator-lifecycle-manager/index.json

fix autoscaling api and link to upstream finalizer examples

fix autoscaling api and link to upstream finalizer examples

---

middleware/middleware-kogito/optaplanner-knapsack/01-create-project.md
middleware/middleware-kogito/rest-service-integration/01-create-project.md
middleware/middleware-kogito/rest-service-integration/04-implement-camel-client.md

Kogito scenario's using the 1.3.1 Quarkus Maven Plugin project generation were broken.

Kogito quarkus upgrade

---

developing-on-openshift/serverless/01-prepare.md

fixes the login image URL and corrects the spelling for "remember"

fix for #859

---

external/citrus/intro/finish.md
external/citrus/intro/intro.md
external/citrus/intro/step0.md
external/citrus/intro/step3.md
external/citrus/intro/step4.md

Fixed some typos and did some minor content updates.

[Citrus Scenario] Typo changes

---

training/full-day-pathway.json

This is the pathway for https://github.com/openshift-labs/learn-katacoda/issues/874

adding training pathway for a full-day workshop

---

playgrounds-pathway.json
playgrounds/openshift45/finish.md
playgrounds/openshift45/index.json
playgrounds/openshift45/intro.md
playgrounds/openshift45/set-env.sh
playgrounds/openshift45/tips.md

OpenShift 4.5 Playground

---

ai-machine-learning/prometheus-api-client/01-loading-the-notebook-images.md
ai-machine-learning/prometheus-timeseries-forecasting/intro.md

Updating the scenario instructions

[ai/prometheus-api-client/timeseries-forecasting] Update the pad workshop instructions

---

ansibleop/ansible-mcrouter-operator/step3.md

replace the jess/telnet image with rhel8/support-tools image, also specify a non-zero expiration time to memcache key and add a little explanatory text
fixes #875 
i'm not sure if there is a more slender image than this that would be preferable

replace broken telnet image

---

ansibleop/ansible-k8s-modules/index.json
ansibleop/ansible-mcrouter-operator/index.json
ansibleop/ansible-operator-overview/index.json
operatorframework/etcd-operator/index.json
operatorframework/go-operator-podset/assets/podset_controller.go
operatorframework/go-operator-podset/assets/podset_types.go
operatorframework/go-operator-podset/index.json
operatorframework/go-operator-podset/step3.md
operatorframework/go-operator-podset/step4.md
operatorframework/go-operator-podset/step5.md
operatorframework/helm-operator/index.json
operatorframework/helm-operator/step3.md
operatorframework/k8s-api-fundamentals/index.json
operatorframework/operator-lifecycle-manager/index.json

Bump Operator Framework exercises backend image to 4.5 and additional corrections/typos

Bump Operator Framework exercises backend image to 4.5 and additional corrections

---

environments/openshift-4-6/client/build/1_packages.sh
environments/openshift-4-6/client/build/3_op-sdk-setup.sh
playgrounds/openshift46/finish.md
playgrounds/openshift46/index.json
playgrounds/openshift46/intro.md
playgrounds/openshift46/set-env.sh
playgrounds/openshift46/tips.md

adding the ocp46 playground.
this is not linked to a pathway yet.

OCP46 playground

---

enterprise-java-pathway.json

Add the Kafka course to the enterprise java pathway

add kafka path to enterprise-java

---

branded-ui/katacoda/main.go

This will fix an issue for redirecting courses.

Fix redirection for courses

---

branded-ui/katacoda/redirect.go

This will fix an issue for redirecting /operators to /operatorframework.

Update for course redirection

---

middleware/middleware-kafka-pathway.json
middleware/middleware-kafka/kafka-quarkus/assets/kafka-cluster.yaml
middleware/middleware-kafka/kafka-quarkus/assets/operator-install.yaml
middleware/middleware-kafka/kafka-quarkus/assets/strimzi-admin.yaml
middleware/middleware-kafka/kafka-quarkus/env-init.sh
middleware/middleware-kafka/kafka-quarkus/finish.md
middleware/middleware-kafka/kafka-quarkus/index.json
middleware/middleware-kafka/kafka-quarkus/intro.md
middleware/middleware-kafka/kafka-quarkus/set-env.sh
middleware/middleware-kafka/kafka-quarkus/step1.md
middleware/middleware-kafka/kafka-quarkus/step2.md
middleware/middleware-kafka/kafka-quarkus/step3.md
middleware/middleware-kafka/kafka-quarkus/step4.md

New scenario to add to the kafka path
- Create a kafka producer using quarkus and the MP Reactive Messaging
You can try it here: https://katacoda.com/hguerrero/courses/middleware/middleware-kafka/kafka-quarkus

Kafka quarkus

---

middleware/middleware-kafka/kafka-debezium/01-deploying-a-broker.md
middleware/middleware-kafka/kafka-debezium/02-deploying-a-kafka-connect.md
middleware/middleware-kafka/kafka-debezium/index.json
middleware/middleware-kafka/kafka-debezium/set-env.sh

add a script to wait for the files to exist before users can start working with the scenario.

wait for files to start

---

middleware/middleware-camelk/camel-k-eventing/step2.md

Fixing Camel K 1.2.1 POJO issue
https://github.com/openshift-labs/learn-katacoda/issues/974

[BUG FIX] issues/974

---

middleware/pipelines/01install-op.md

https://docs.openshift.com/container-platform/4.5/pipelines/installing-pipelines.html#op-installing-pipelines-operator-using-the-cli_installing-pipelines

Fix channel name

---

middleware/middleware-kafka-pathway.json
middleware/middleware-kafka/kafka-basic/finish.md
middleware/middleware-kafka/kafka-basic/intro.md
middleware/middleware-kafka/kafka-basic/step1.md
middleware/middleware-kafka/kafka-basic/step2.md
middleware/middleware-kafka/kafka-basic/step3.md
middleware/middleware-kafka/kafka-basic/step4.md
middleware/middleware-kafka/kafka-debezium/01-deploying-a-broker.md
middleware/middleware-kafka/kafka-http-bridge/env-init.sh
middleware/middleware-kafka/kafka-quarkus/env-init.sh

Signed-off-by: prmellor <pmellor@redhat.com>
Editorial review of the _Apache Kafka Basics_ scenario

Kafka review - Course #1 edits

---

introduction/developing-with-odo-1/00-application-overview.md
introduction/developing-with-odo-1/01-creating-initial-project.md
introduction/developing-with-odo-1/02-creating-new-binary-component.md
introduction/developing-with-odo-1/03-deploying-component-from-source-code.md
introduction/developing-with-odo-1/04-linking-components.md
introduction/developing-with-odo-1/05-exposing-components-to-public.md
introduction/developing-with-odo-1/06-making-changes-to-source-code.md
introduction/developing-with-odo-1/assets/volumes.json
introduction/developing-with-odo-1/env-init.sh
introduction/developing-with-odo-1/finish.md
introduction/developing-with-odo-1/index.json
introduction/developing-with-odo-1/intro.md
introduction/developing-with-odo-1/set-env.sh

First steps:
- [*] create a backup of odo v1 content: `introduction/developing-with-odo-1`
- [*] update the backend.imageid in `index.json` to "4.6"
TODO:

Updating odo scenario for odo v2.x

---

introduction/developing-with-odo/02-creating-new-binary-component.md
introduction/developing-with-odo/03-deploying-component-from-source-code.md
introduction/developing-with-odo/04-linking-components.md
introduction/developing-with-odo/05-exposing-components-to-public.md
introduction/developing-with-odo/intro.md

cleanup scenario content for odo 2.0

odo 2.0 scenario updates

---

environments/openshift-4-4/master/build/6_ocs-pull.sh
environments/openshift-4-6/master/build/6_ocs-pull.sh
persistence/persistent-elasticsearch/assets/install_ocs.sh
persistence/persistent-elasticsearch/index.json
persistence/persistent-intro/assets/install_ocs.sh
persistence/persistent-intro/index.json
persistence/persistent-intro/intro.md
persistence/persistent-intro/obc.md
persistence/persistent-intro/rwx.md

This fixes the OCS labs not being able to provision on learn.openshift.com
Edit:
You can test this PR at https://www.katacoda.com/storage/courses/persistence

Update OCS labs to OCP 4.6

---

training/developing-on-openshift-pathway.json

Workshop requested by Koen C. van Bakel. PRINCIPAL SOLUTION ARCHITECT. Red Hat The Netherlands
Signed-off-by: Gabriela S. Soria <soria.gaby@gmail.com>

Add pathway file for Developing on OpenShift Workshop

---

middleware/middleware-kafka/kafka-http-bridge/intro.md
middleware/middleware-kafka/kafka-http-bridge/step1.md
middleware/middleware-kafka/kafka-http-bridge/step2.md
middleware/middleware-kafka/kafka-http-bridge/step3.md
middleware/middleware-kafka/kafka-http-bridge/step4.md

Signed-off-by: prmellor <pmellor@redhat.com>
Editorial review of the _Exposing Apache Kafka through the HTTP Bridge_ scenario

Kafka review - Course #2 edits

---

introduction/cluster-access-36/04-switching-between-accounts.md
introduction/cluster-access/04-switching-between-accounts.md

Updated wording. This might read a little bit better - although the original may not be incorrect to begin with.

Updated wording to something that might sound better

---

persistence/persistent-elasticsearch/01.md
persistence/persistent-elasticsearch/02.md
persistence/persistent-elasticsearch/04.md
persistence/persistent-elasticsearch/assets/install_ocs.sh
persistence/persistent-elasticsearch/index.json
persistence/persistent-elasticsearch/intro.md
persistence/persistent-intro/assets/install_ocs.sh
persistence/persistent-intro/finish.md
persistence/persistent-intro/obc.md
persistence/persistent-intro/rwo.md
persistence/persistent-intro/rwx.md

Not sure why there are additional commits in the change list, since these were merged in https://github.com/openshift-labs/learn-katacoda/pull/1036
This should only contain OCS->ODF text changes from 4d2fb68

OCS -> ODF rebrand

---

eventdriven-with-kafka-pathway.json
homepage-pathway.json

move the Kafka Katacodas to the top level.

Kafka to frontpage

---

middleware/middleware-kafka/kafka-quarkus/index.json
middleware/middleware-kafka/kafka-quarkus/intro.md
middleware/middleware-kafka/kafka-quarkus/step1.md
middleware/middleware-kafka/kafka-quarkus/step2.md
middleware/middleware-kafka/kafka-quarkus/step3.md
middleware/middleware-kafka/kafka-quarkus/step4.md

Signed-off-by: prmellor <pmellor@redhat.com>
Editorial review of the _Apache Kafka with Reactive Messaging_ scenario

Kafka review - Course #3 edits

---

gitops-pathway.json
homepage-pathway.json

- Add GitOps path into homepage
- Add Pipelines scenario intro GitOps path
- Added Pipelines to the description of the GitOps path

Refactor CI/CD into GitOps path

---

middleware/middleware-kafka/kafka-basic/index.json
middleware/middleware-kafka/kafka-debezium/00-intro.md
middleware/middleware-kafka/kafka-debezium/01-deploying-a-broker.md
middleware/middleware-kafka/kafka-debezium/02-deploying-a-kafka-connect.md
middleware/middleware-kafka/kafka-debezium/03-streaming-data-from-database.md
middleware/middleware-kafka/kafka-debezium/99-outro.md
middleware/middleware-kafka/kafka-http-bridge/index.json
middleware/middleware-kafka/kafka-quarkus/index.json

Signed-off-by: prmellor <pmellor@redhat.com>
Editorial review of the _Debezium for change data capture_ scenario

Kafka review - Course #4 edits

---

gitops/syncwaves-hooks/03-using-syncwaves-and-hooks.md

Adding `shell` to the code block.

Fix code block

---

ai-machine-learning/custom-notebooks/index.json
ai-machine-learning/jupyter-notebooks/index.json
ai-machine-learning/jupyter-workspace/index.json
ai-machine-learning/jupyterhub-service/index.json
ai-machine-learning/jupyterhub-workspace/index.json
introduction/cluster-access/index.json
introduction/deploy-prometheus-grafana/index.json
introduction/deploying-images/index.json
introduction/deploying-python/index.json
introduction/developing-with-odo/index.json
introduction/getting-started/index.json
introduction/port-forwarding/index.json
introduction/resource-objects/index.json
introduction/transferring-files/index.json
middleware/middleware-quarkus/panache/index.json
persistence/persistent-elasticsearch/index.json
persistence/persistent-intro/index.json

Move the 4-6 scenarios to the latest release

Roll openshift-4-6 scenarios to openshift-4-7

---

developing-on-openshift/helm/00-intro.md
developing-on-openshift/helm/99-outro.md
developing-on-openshift/helm/index.json

updating this section to openshift-4-7

helm to openshfit-4-7

---

middleware/pipelines/set-env.sh

optionally install tkn when needed

tkn client missing from "openshift-4-7-client" image

---

developing-on-openshift/helm/00-intro.md
developing-on-openshift/helm/02-first-chart.md
developing-on-openshift/helm/03-revision.md
developing-on-openshift/helm/99-outro.md
developing-on-openshift/helm/set-env.sh

* Add topic page links
* Fix path issue

Helm update

---

middleware/middleware-quarkus/getting-started/index.json
middleware/middleware-quarkus/kafka/index.json
middleware/middleware-quarkus/monitoring/index.json
middleware/middleware-quarkus/qute/index.json
middleware/middleware-quarkus/reactive-sql/index.json
middleware/middleware-quarkus/spring/index.json

bump the openshift version for all quarkus content to 4.7 #1140

quarkus content from 4-4 to 4-7

---

operatorframework/go-operator-memcached/index.json

Didn't realize that I didn't change the openshift version. Sorry!!!

change from 4-5 to 4-7

---

summit-pathway.json

Adding a landing page for RHSummit 2021:
https://learn.openshift.com/summit
QA review checklist:

new summit-pathway.json for RHSummit 2021

---

operatorframework/etcd-operator/finish.md
operatorframework/etcd-operator/index.json
operatorframework/etcd-operator/intro.md
operatorframework/go-operator-podset/index.json
operatorframework/helm-operator/index.json
operatorframework/operator-lifecycle-manager/index.json

Reverts openshift-labs/learn-katacoda#1150
To avoid breakage, will revert version changes and add in text changes in a future PR

Revert etcd to 4-7

---

ai-machine-learning/thoth-s2i-advise/index.json
ai-machine-learning/thoth-s2i-provenance/index.json

AI/ML to openshift-47

---

ai-machine-learning/prometheus-api-client/index.json
ai-machine-learning/prometheus-timeseries-forecasting/index.json

prometheus content to openshfit-4-7

bump prometheus content to openshfit-4-7

---

middleware/middleware-kogito/dmn/index.json
middleware/middleware-kogito/getting-started/index.json
middleware/middleware-kogito/optaplanner-knapsack/index.json
middleware/middleware-kogito/rest-service-integration/index.json
middleware/middleware-kogito/rules/index.json
middleware/middleware-kogito/service-task-cdi/index.json

Kogito to 47

---

introduction/developing-with-odo/set-env.sh

fixing copy/paste (error due to linewraps).  Thanks for the alert, @cedricclyburn!

short-term fix for #1136

---

developing-on-openshift/serverless/assets/01-prepare/watch-serverless-operator.bash

Was having issues with the install script recognizing the serverless operator was successfully installed, this should fix 👍

Fix for the infinite "Checking" issue on Serverless

---

developing-on-openshift/serverless/assets/01-prepare/install-serverless.bash

Serverless prepare script creates error, minor fix

Serverless prepare script creates duplicate project creation, throws error

---

middleware/middleware-spring-boot/spring-db-access/00-intro.md
middleware/middleware-spring-boot/spring-db-access/01-review-the-initial-project.md
middleware/middleware-spring-boot/spring-db-access/02-read-content-from-a-database.md
middleware/middleware-spring-boot/spring-db-access/03-deploy-to-openshift.md
middleware/middleware-spring-boot/spring-db-access/env-init.sh
middleware/middleware-spring-boot/spring-db-access/index.json
middleware/middleware-spring-boot/spring-db-access/set-env.sh

Part of #1060 - Spring Data with JPA
Goes along with openshift-katacoda/rhoar-getting-started#61, openshift-katacoda/rhoar-getting-started#62, & openshift-katacoda/rhoar-getting-started#62

Update to Spring Data JPA course

---

middleware/middleware-spring-boot/spring-db-access/02-read-content-from-a-database.md
middleware/middleware-spring-boot/spring-db-access/03-deploy-to-openshift.md

Spring Data JPA

---

subsystems/container-internals-lab-2-0-part-1/index.json
subsystems/container-internals-lab-2-0-part-2/index.json
subsystems/container-internals-lab-2-0-part-3/index.json
subsystems/container-internals-lab-2-0-part-4/index.json
subsystems/container-internals-lab-2-0-part-5/index.json
subsystems/container-internals-lab-2-0-part-6/index.json
subsystems/container-internals-lab-2-0-part-7/index.json

temporarily moving subsystems content to v3.7

311 DOWNgrade

---

subsystems/container-internals-lab-2-0-part-2/01-base-multi-layer-images.md
subsystems/container-internals-lab-2-0-part-2/02-image-urls.md
subsystems/container-internals-lab-2-0-part-2/03-image-internals.md
subsystems/container-internals-lab-2-0-part-2/finish.md
subsystems/container-internals-lab-2-0-part-2/intro.md

Fixed various different typos in the scenario, addressing #1170

Typos in the container registry scenario

---

middleware/middleware-quarkus/panache/01-define-entity.md

Resource classes don't need @ApplicationScoped

Resource classes don't need @ApplicationScoped

---

middleware/middleware-quarkus/panache/03-add-query-endpoints.md

Remove persistent from results

Remove persistent from results

---

middleware/middleware-quarkus/panache/04-add-paging-filtering.md

Removing persistent from output

Removing persistent from output

---

middleware/middleware-spring-boot/spring-getting-started/02-read-content-from-a-database.md
middleware/middleware-spring-boot/spring-getting-started/03-create-rest-services.md
middleware/middleware-spring-boot/spring-getting-started/05-deploy-to-openshift.md

Fix the Spring getting-started scenario

Fix Spring getting-started

---

ai-machine-learning/custom-notebooks/env-init.sh
ai-machine-learning/jupyter-notebooks/env-init.sh
ai-machine-learning/jupyter-workspace/env-init.sh
ai-machine-learning/jupyterhub-service/env-init.sh
ai-machine-learning/jupyterhub-workspace/env-init.sh

- Move to [openshift-katacoda](https://github.com/openshift-katacoda/)
- Update postgresql image tag
- Fixes #1244 #1245 
As part of: https://github.com/openshift-labs/learn-katacoda/issues/1213

Move jupyter demos to openshift-katacoda

---

middleware/middleware-spring-boot/spring-getting-started/03-create-rest-services.md
middleware/middleware-spring-boot/spring-getting-started/05-deploy-to-openshift.md
middleware/middleware-spring-boot/spring-rest-services/02-create-rest-services.md

Spring scenarios: Some cleanup/typo fixes

---

middleware/middleware-quarkus/getting-started/04-build-native.md
middleware/middleware-quarkus/monitoring/02-create-and-instrument-app.md
middleware/middleware-quarkus/qute/01-basics.md
middleware/middleware-quarkus/spring/01-create-project.md

Remove dates from listing output

Remove dates

---

training/using-the-cluster-pathway.json

typical pathway to training pathway edits

Edits for training/using-the-cluster-pathway.json

---

middleware/middleware-kafka/kafka-http-bridge/assets/kafka-bridge.yaml
middleware/middleware-kafka/kafka-http-bridge/assets/kafka-cluster.yaml
middleware/middleware-kafka/kafka-quarkus/assets/kafka-cluster.yaml

update kafka cr to latest apiversion
